name: technician_app
description: A Service Management App for Technicians
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  firebase_database: ^10.2.1
  shared_preferences: ^2.1.1
  google_sign_in: ^6.1.0
  audioplayers: ^5.2.1
  # cloud_firestore: ^4.7.1  # Using Realtime Database instead for free tier
  # firebase_storage: ^11.2.1  # Not using storage for free version
  provider: ^6.1.1
  intl: ^0.18.1
  image_picker: ^0.8.7+4
  signature: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/job_alert.mp3